language: java

# Skip "install" stage:
install: true

# Use container-based infrastructure:
sudo: false

dist: precise
addons:
  hosts:
    - travis
  hostname: travis

# Keep Maven local repository between builds:
cache:
  directories:
    - '$HOME/.m2/repository'

env:
  - JDK=5
  - JDK=6
  - JDK=7
  - JDK=8
  - JDK=8
    ECJ=true
  - JDK=8-ea
  - JDK=9

matrix:
  allow_failures:
    - env: JDK=8-ea

script: ./.travis.sh
